
package com.wondersgroup.healthcloud.familydoctor.services.sign;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebServiceClient(name = "QianyueImplService", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", wsdlLocation = "http://218.89.178.119:8088/fjzl/webservice/qianyue?wsdl")
public class QianyueImplService
        extends Service {

    private final static URL QIANYUEIMPLSERVICE_WSDL_LOCATION = null;
    private final static WebServiceException QIANYUEIMPLSERVICE_EXCEPTION = null;
    private final static QName QIANYUEIMPLSERVICE_QNAME = new QName("http://webservice.fjzl.wondersgroup.com/", "QianyueImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://218.89.178.119:8088/fjzl/webservice/qianyue?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
//        QIANYUEIMPLSERVICE_WSDL_LOCATION = url;
//        QIANYUEIMPLSERVICE_EXCEPTION = e;
    }

    public QianyueImplService() {
        super(__getWsdlLocation(), QIANYUEIMPLSERVICE_QNAME);
    }

    public QianyueImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QIANYUEIMPLSERVICE_QNAME, features);
    }

    public QianyueImplService(URL wsdlLocation) {
        super(wsdlLocation, QIANYUEIMPLSERVICE_QNAME);
    }

    public QianyueImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QIANYUEIMPLSERVICE_QNAME, features);
    }

    public QianyueImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QianyueImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns QianyueInterface
     */
    @WebEndpoint(name = "QianyueImplPort")
    public QianyueInterface getQianyueImplPort() {
        return super.getPort(new QName("http://webservice.fjzl.wondersgroup.com/", "QianyueImplPort"), QianyueInterface.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns QianyueInterface
     */
    @WebEndpoint(name = "QianyueImplPort")
    public QianyueInterface getQianyueImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.fjzl.wondersgroup.com/", "QianyueImplPort"), QianyueInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QIANYUEIMPLSERVICE_EXCEPTION != null) {
            throw QIANYUEIMPLSERVICE_EXCEPTION;
        }
        return QIANYUEIMPLSERVICE_WSDL_LOCATION;
    }

}
