
package com.wondersgroup.healthcloud.familydoctor.services.referral;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "ZhuanzhenInterface", targetNamespace = "http://webservice.fjzl.wondersgroup.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface ZhuanzhenInterface {


    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "inpatientApply", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.wondersgroup.healthcloud.familydoctor.services.referral" +
            ".InpatientApply")
    @ResponseWrapper(localName = "inpatientApplyResponse", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.wondersgroup.healthcloud.familydoctor.services.referral" +
            ".InpatientApplyResponse")
    public String inpatientApply(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "outpatientAction", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.wondersgroup.healthcloud.familydoctor.services.referral" +
            ".OutpatientAction")
    @ResponseWrapper(localName = "outpatientActionResponse", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.wondersgroup.healthcloud.familydoctor.services.referral" +
            ".OutpatientActionResponse")
    public String outpatientAction(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "outpatientList", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.wondersgroup.healthcloud.familydoctor.services.referral" +
            ".OutpatientList")
    @ResponseWrapper(localName = "outpatientListResponse", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.wondersgroup.healthcloud.familydoctor.services.referral" +
            ".OutpatientListResponse")
    public String outpatientList(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "inpatientList", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.wondersgroup.healthcloud.familydoctor.services.referral.InpatientList")
    @ResponseWrapper(localName = "inpatientListResponse", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.wondersgroup.healthcloud.familydoctor.services.referral" +
            ".InpatientListResponse")
    public String inpatientList(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "outpatientApply", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.wondersgroup.healthcloud.familydoctor.services.referral" +
            ".OutpatientApply")
    @ResponseWrapper(localName = "outpatientApplyResponse", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.wondersgroup.healthcloud.familydoctor.services.referral" +
            ".OutpatientApplyResponse")
    public String outpatientApply(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "outpatientDetail", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.wondersgroup.healthcloud.familydoctor.services.referral" +
            ".OutpatientDetail")
    @ResponseWrapper(localName = "outpatientDetailResponse", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.wondersgroup.healthcloud.familydoctor.services.referral" +
            ".OutpatientDetailResponse")
    public String outpatientDetail(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "inpatientAction", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.wondersgroup.healthcloud.familydoctor.services.referral" +
            ".InpatientAction")
    @ResponseWrapper(localName = "inpatientActionResponse", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.wondersgroup.healthcloud.familydoctor.services.referral" +
            ".InpatientActionResponse")
    public String inpatientAction(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "inpatientDetail", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.wondersgroup.healthcloud.familydoctor.services.referral" +
            ".InpatientDetail")
    @ResponseWrapper(localName = "inpatientDetailResponse", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.wondersgroup.healthcloud.familydoctor.services.referral.InpatientDetailResponse")
    public String inpatientDetail(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

}
