server:
  port: 3902
  contextPath: /wondersgroup-SC-jobclient
  tomcat:
    uri-encoding: UTF-8


lts:
  jobclient:
    cluster-name: healthSC-job
    registry-address: zookeeper://zookeeper1.we-jk.me:2181,zookeeper2.we-jk.me:2181,zookeeper3.we-jk.me:2181
    node-group: healthSC_jobClient
    tasknodegroup: healthSC_tasktracker
    dataPath: /usr/src/lts/failstore
    use-retry-client: true
    configs:
      job:
        fail:
          store: leveldb


mysql:
  connection:
    url: jdbc:mysql://mysql-m.we-jk.me:5500/healthcloud_sc_server?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull
    username: health
    password: PassWord

qiniu:
  access_key: uWCBSNid5ZGbs1exNGwoV9oCfvz3embV5lfojnog
  secret_key: 7ms0V8Lk4S1goqClOaFL9mJmoOeMOwhdl3Zfi_XV
  bucket: healthcloud
  domain: http://og3xulzx6.bkt.clouddn.com/

spring:
  mail:
    sendFrom: wondershealth@wondersgroup.com
    username: wondershealth
    password: Wonders@2009
    host: pop3.wondersgroup.com
    port: 587