
package com.wondersgroup.healthcloud.familydoctor.services.referral;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ZhuanzhenImplService", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", wsdlLocation = "http://218.89.178.119:8088/fjzl/webservice/zhuanzhen?wsdl")
public class ZhuanzhenImplService
        extends Service {

    private final static URL ZHUANZHENIMPLSERVICE_WSDL_LOCATION = null;
    private final static WebServiceException ZHUANZHENIMPLSERVICE_EXCEPTION= null;
    private final static QName ZHUANZHENIMPLSERVICE_QNAME = new QName("http://webservice.fjzl.wondersgroup.com/", "ZhuanzhenImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://218.89.178.119:8088/fjzl/webservice/zhuanzhen?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
//        ZHUANZHENIMPLSERVICE_WSDL_LOCATION = url;
//        ZHUANZHENIMPLSERVICE_EXCEPTION = e;
    }

    public ZhuanzhenImplService() {
        super(__getWsdlLocation(), ZHUANZHENIMPLSERVICE_QNAME);
    }

    public ZhuanzhenImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZHUANZHENIMPLSERVICE_QNAME, features);
    }

    public ZhuanzhenImplService(URL wsdlLocation) {
        super(wsdlLocation, ZHUANZHENIMPLSERVICE_QNAME);
    }

    public ZhuanzhenImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZHUANZHENIMPLSERVICE_QNAME, features);
    }

    public ZhuanzhenImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZhuanzhenImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns ZhuanzhenInterface
     */
    @WebEndpoint(name = "ZhuanzhenImplPort")
    public ZhuanzhenInterface getZhuanzhenImplPort() {
        return super.getPort(new QName("http://webservice.fjzl.wondersgroup.com/", "ZhuanzhenImplPort"), ZhuanzhenInterface.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ZhuanzhenInterface
     */
    @WebEndpoint(name = "ZhuanzhenImplPort")
    public ZhuanzhenInterface getZhuanzhenImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.fjzl.wondersgroup.com/", "ZhuanzhenImplPort"), ZhuanzhenInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZHUANZHENIMPLSERVICE_EXCEPTION != null) {
            throw ZHUANZHENIMPLSERVICE_EXCEPTION;
        }
        return ZHUANZHENIMPLSERVICE_WSDL_LOCATION;
    }

}
