server:
  port: 3900
  contextPath: /healthSC-jobtracker
  tomcat:
    uri-encoding: UTF-8

lts:
  jobtracker:
    cluster-name: healthSC-job
    listen-port: 35009
    registry-address: zookeeper://zookeeper1.we-jk.me:2181,zookeeper2.we-jk.me:2181,zookeeper3.we-jk.me:2181
    dataPath: /usr/src/lts/failstore
    configs:
        logger: mysql
        queue: mysql
        jdbc:
          url: jdbc:mysql://mysql-m.we-jk.me:5500/healthSC_lts
          username: health
          password: PassWord